### ISSUE TITLE
Retries Not Woking

### ISSUE THREAD

**Issue by psmod2** [webdriverio/wdio-mocha-framework#142]
Hi,

Mocha's retries doesn't seem to work.

Using wdio-mocha-framework@0.5.12 and webdriverio@4.10.1

So in my wdio.conf I have:

```
mochaOpts: {
    ui: 'bdd',
    timeout: config.get('timeout'),
    retries: 3
}
```

And have a basic test:

```
it('Retry working?', function () {
    var a = 1
    expect(a).to.equal(2)
}
```

It only runs once - even if I place the line `this.retries(3)` in the it block it doesnt work.

Any ideas?

**Comment by christian-bromann** [comment]
This works for me. Have you tried to put a console.log in there? Then you will see that it will get executed 3 times.
