### ISSUE TITLE
Support an equivalent to --exit for Mocha

### ISSUE THREAD

**Issue by marcelas** [webdriverio/wdio-mocha-framework#144]
From the command line, mocha supports an '--exit' parameter that kills the process on exit. This is important to avoid having the process hanging: https://mochajs.org/#--exit----no-exit
When this happens with wdio, mocha hangs and the test run never completes. We should either allow the caller to configure a callback function on Mocha.run to simulate that, orhave an exit configuration and handle the force exit process on this library.

**Comment by christian-bromann** [comment]
you can apply it within mochaOpts in your wdio config:
```js
mochaOpts: {
  exit: true
}
```

**Comment by marcelas** [comment]
@christian-bromann I don't think that would work, exit is not on one of the supported mocha options: https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options.
That command line option is only parsed by https://github.com/mochajs/mocha/blob/9d407deb77d9f6bdc44928e25dd8a739069d6a0d/bin/_mocha#L222
and https://github.com/mochajs/mocha/blob/9d407deb77d9f6bdc44928e25dd8a739069d6a0d/bin/_mocha#L650

**Comment by christian-bromann** [comment]
Well there is no such equivalent in WebdriverIO. WebdriverIO spawns multiple processes and can't just kill all of them once one of the others fail. What is your use case here exactly?

**Comment by marcelas** [comment]
My suggestion is to pass a callback function on mocha.run call from the adapter (https://github.com/webdriverio/wdio-mocha-framework/blob/master/lib/adapter.js#L106) similar to the one that _mocha is using:

> const exit = code => {
  const clampedCode = Math.min(code, 255);
  let draining = 0;

  // Eagerly set the process's exit code in case stream.write doesn't
  // execute its callback before the process terminates.
  process.exitCode = clampedCode;

  // flush output for Node.js Windows pipe bug
  // https://github.com/joyent/node/issues/6247 is just one bug example
  // https://github.com/visionmedia/mocha/issues/333 has a good discussion
  const done = () => {
    if (!draining--) {
      process.exit(clampedCode);
    }
  };

  const streams = [process.stdout, process.stderr];

  streams.forEach(stream => {
    // submit empty write request and wait for completion
    draining += 1;
    stream.write('', done);
  });

  done();
};

My use case here is: about 15% of my webdriverio test runs never exit because the mocha doesn't exit so webdriver never ends the runner ("suite:end" fires but "runner:ends" doesn't).

**Comment by christian-bromann** [comment]
> My use case here is: about 15% of my webdriverio test runs never exit

Why is that?

**Comment by marcelas** [comment]
> >My use case here is: about 15% of my webdriverio test runs never exit

> Why is that?

because the mocha doesn't exit :)  This a known behavior in mocha and their solution for it is the exit flag. What I am asking is to have a way for me to do the same.

**Comment by christian-bromann** [comment]
@marcelas tests that are getting executed synchronously usually never get stalen .. do you have a reproducible example?

**Comment by christian-bromann** [comment]
Also .. we always call process.exit in the testrunner per default
