### ISSUE TITLE
wdio doesn't run the mocha root suite hooks

### ISSUE THREAD

**Issue by graingert** [webdriverio/wdio-mocha-framework#15]
See this example project:

https://github.com/graingert/wdio-mocha-root-suite-hook

hooks defined putside of any define in any spec file should be run before anything else:

```js
before(function () {
  global.didRunBeforeHook = true;
});
```

```js
var expect = require('chai').expect;

describe('test suite', function() {
  it('test case', function (){
    expect(global.didRunBeforeHook).to.be.true
  });
});
```

**Comment by graingert** [comment]
@christian-bromann these tests used to pass in webdriverio@3

**Comment by christian-bromann** [comment]
Well something like this is not really working in v4 either giving the fact that wdio creates a new session for each spec file. Sorry
