### ISSUE TITLE
Mocha timeout option is ignored

### ISSUE THREAD

**Issue by ianrenauld** [webdriverio/wdio-mocha-framework#18]
I have a test with a page that takes fairly long to fully load (for example: http://www.saksfifthavenue.com/). It oftentimes takes more than 10 seconds to get all the widgets, pop-ups and everything fully loaded.  In these cases, I get the following error message (just on trying to load the page - I have not started interacting with the page):

Blablabla test suite "before all" hook:
timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
running chrome
Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
    at Timeout.<anonymous> (/usr/local/lib/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:226:19)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

I tried changing the mocha timeout in wdio.conf.js as described in the http://webdriver.io/guide/testrunner/timeouts.html page:

    framework: 'mocha',
    mochaOpts: {
        timeout: 99999999
    },

But no matter which value is given to timeout (I tried 20000, 0 and other big numbers), it still times out after 10 seconds.

I switched to using Jasmine instead, changed the Jasmine timeout to 20 seconds (as it still fails occasionally if I keep the 10 seconds default value) and everything works fine.

It looks to me like the mocha timeout value in wdio.conf.js is not being passed correctly to mocha itself.

I think I am using the latest version of all components:
mocha: 2.5.3
wdio-mocha-framework: 0.3.5
webdriverio: 4.2.1

**Comment by monolithed** [comment]
```js
{
	"webdriverio" : "^4.2.1",
	"wdio-mocha-framework" : "^0.3.5",
}
```

Works fine for me.
I'm not sure, but have you tried `waitforTimeout: 999999` ?

**Comment by ianrenauld** [comment]
Yes, I did try to raise all the timeout values (including waitforTimeout), but these other timeouts are not the ones causing the issue (I am not actually running any waitfor... commands, I am still just waiting for the page to load).  Mocha timeout seems to trip up before all others.  When I switched to Jasmine, I reset all the other timeouts and I have no issues on page load (well as long as I raise the Jasmine framework timeout above 10 seconds, of course).

I am not really required to use Mocha, Jasmine is perfectly fine.  I just raised the issue in case I am not the only one seeing this (and others might require the use of Mocha).

**Comment by christian-bromann** [comment]
@ianrenauld it is working for me to. Are you using the wdio testrunner?

**Comment by ianrenauld** [comment]
Yes I am using the wdio test runner.

If someones wants to reproduce what I am seeing, here is a simplification of my code that does the problem for me (maybe not 100% of the time: we need the web site to take slightly more than 10 seconds to load, but it happens often enough).  Increasing Mocha timeout does not help, but increasing the timeout in Jasmine does work.

```javascript
describe('Test Suite', function () {

    it('Open the web page', function () {
        browser.url('http://www.saksfifthavenue.com/Entry.jsp?sf_ip=50.73.157.179');
        if (browser.element('[id="modal"]').isVisible) {
            browser.element('[id="closeButton"]').click();
            // Pause for the animation that closes the window
            browser.pause(250);
        }
        browser.waitForVisible('[id="sf-widget-companion"]');
        browser.frame('sf-widget-companion');

        if (browser.element('.sidebar2.js-sidebar-widget.desktop.sidebar2--close-desktop').isVisible()) {
            browser.element('.sidebar2.js-sidebar-widget.desktop.sidebar2--close-desktop').click();
        }

    });
});
```

**Comment by christian-bromann** [comment]
@ianrenauld can you execute `console.log(browser.options)` and post the result here?

**Comment by ianrenauld** [comment]
Found the issue while printing out my browser.options.  Seems that I had two different sections for mochaOpts in my config file.  The first one set the timeout, while the second one set the ui to bdd.  But since there was no timeout values in that block, it reset to 10000.

When I combine the two, all is fine.  Thanks for your help!

**Comment by megamindbrian** [comment]
I am getting this error but only 1 mocha config section.
