### ISSUE TITLE
no such session

### ISSUE THREAD

**Issue by rossPatton** [webdriverio/wdio-mocha-framework#20]
getting this error while attempting to use this module with webdriverio

```shell
Error: no such session
    at Object.Future.wait (/path/to/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers/future.js:449:15)
    at Object.close (/path/to/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:353:31)
    at Object.exports.config.after (/path/to/wdio.conf.js:190:15)
    at /path/to/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:251:34
```

using 0.3.5, with webdriverio 4.2.1

**Comment by rossPatton** [comment]
what's worse is all tests are passing, even though no test are being actually run

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by rossPatton** [comment]
sure, i guess i could post my `wdio.conf.js` file and an example of some of my tests?

[my wdio.conf.js](https://gist.github.com/rossPatton/e1028fe4138a2d4ea23246b7e4a23980)

[example test code](https://gist.github.com/rossPatton/ba89379c6f729e471d427d248afca095)

You can see in the test code that I am validating that a fax is being rendered correctly. But the fax has been completely redesigned - yet tests still pass. I can even put in impossible selectors and they still pass. Unfortunately I can't post the actual html / fax I am testing against, but hopefully this helps.

All of my testing files have this same structure, and I only recently upgraded to webdriver 4 (and before that I did not use wdio-mocha-framework). Prior to upgrading everything worked as expected

**Comment by christian-bromann** [comment]
WebdriverIO v4.x doesn't support generators anymore. So I think the reason why all your tests are passing is that no test is actually executed. Please remove all yields and the `*` and it should be better.
