### ISSUE TITLE
mod.split is not a function

### ISSUE THREAD

**Issue by zdfs** [webdriverio/wdio-mocha-framework#21]
I keep getting this error in 0.3.6, but not in 0.3.5. Broke my build this morning.

**Comment by christian-bromann** [comment]
Do you use `require`?

**Comment by christian-bromann** [comment]
fixing

**Comment by christian-bromann** [comment]
unpublished `v0.3.6`. @monolithed can you please look into it?

**Comment by monolithed** [comment]
Yep, give me 5 minutes

**Comment by christian-bromann** [comment]
Reverted change and will publish new version with bumped wdio-sync

**Comment by monolithed** [comment]
@zdfs, can you show your config?

@christian-bromann, I see that error can be thrown only in the following cases:

```js
require: ['']
require: 'js:unknown_module'
require: './unknown_module'
```

**Comment by christian-bromann** [comment]
I believe `require` is a string array

**Comment by monolithed** [comment]
I know to fix that. But `require` should be a string value unlike `compilers`

**Comment by monolithed** [comment]
>  --compilers <ext>:<module>,...          use the given module(s) to compile files
-r, --require <name>                    require the given module

**Comment by monolithed** [comment]
@christian-bromann, fixed https://github.com/webdriverio/wdio-mocha-framework/pull/22

```
compilers — string[]
require — string
```

**Comment by christian-bromann** [comment]
thanks @monolithed , let's move this convo to #22

**Comment by zdfs** [comment]
Sorry for the late response. Thanks to everyone for fixing this.
