### ISSUE TITLE
Getting error when using this.skip()

### ISSUE THREAD

**Issue by oyvindeh** [webdriverio/wdio-mocha-framework#23]
Using wdio-mocha-framework 0.3.10, I get the following error when using `this.skip()` in tests:

```
TypeError: Cannot read property 'split' of undefined
    at foo/node_modules/wdio-sync/build/index.js:649:30
    at Context.executeSync (/foo/node_modules/wdio-sync/build/index.js:640:12)
    at /foo/node_modules/wdio-sync/build/index.js:877:34
```

This works in older versions of wdio-mocha-framework (<3.0). (The error messages varies in versions from 0.3.0 and up.)

**Comment by christian-bromann** [comment]
We don't support that way of skipping tests, just return and you should be fine. There is also no documentation around this on the Mocha page.

**Comment by oyvindeh** [comment]
Mocha supports it, and they have added documentation: https://mochajs.org/#inclusive-tests (see third example).

**Comment by christian-bromann** [comment]
Ok, I see. Well I will reopen then. I personally think that skipping tests at runtime is a good approach and there are ways how to avoid that. However if someone wants to add support, PRs are welcome.

**Comment by DerFlatulator** [comment]
I find run-time skipping useful for end to end tests that are dependent on configuration that is outside of one's control. This feature would be appreciated.

**Comment by christian-bromann** [comment]
@DerFlatulator you wrap it blocks within if statements

**Comment by oyvindeh** [comment]
To skip the test logic is easy. For me, the key to this feature is to get a hint from the output whether a test is run or not (which you won't get get that with an if clause). Using grep (or defining what tests to run in specs) works, but requires bookkeeping.

I am currently not using `this.skip()`, but my original use case was that we had all our tests run with two different data sets, where some tests could not run with one of the data sets. Using `this.skip()` based on certain conditions, it would be clear to everybody which tests were actually run in each case.

**Comment by christian-bromann** [comment]
So the only "advantage" for you would be that your test is marked as pending instead of not being displayed at all?

Again, PRs are welcome but I definitely won't spend time implementing it as it's not really useful in my eyes.

**Comment by christian-bromann** [comment]
`this.skip` got implemented with recent version.
