### ISSUE TITLE
Error when using require file with es2015 modules

### ISSUE THREAD

**Issue by edmundito** [webdriverio/wdio-mocha-framework#25]
I am unable to get the require file to transpile before being used as shown in the README.md example for this repo. I get the following exception when trying to add a module written in the es2015 syntax:

```
SyntaxError: Unexpected reserved word
```

This is my mocha setup:

``` js
  mochaOpts: {
    ui: 'bdd',
    compilers: ['js:babel-register'],
    require: './wdio-mocha-setup.js'
  }
```

An example `wdio-mocha-setup.js` file:

``` js
import chai from 'chai';
```

**Comment by christian-bromann** [comment]
This is actually a Mocha issue but since we have control over it we could compile the file beforehand and pass it to mocha. However I think this should be fixed on the Mocha side not here. Maybe there is already a solution for it. Closing.

**Comment by dbashford** [comment]
@edmundito any chance you figured this out?

**Comment by edmundito** [comment]
@dbashford Unfortunately, we were not able to resolve this issue so we have moved on by importing a common file on top of every test file as needed.
