### ISSUE TITLE
Error when working with mocha 3.x.x

### ISSUE THREAD

**Issue by przemuh** [webdriverio/wdio-mocha-framework#31]
This is rather future-improvement than critical bug...

Description of the situation:
I have a project where I use wdio-mocha-framework to run functional tests...but I also have mocha installed for my unit tests in the same project. The problem was that I had mocha in version ^3.x.x in my package.json and after last upadate I've got an error:

`[chrome #0-0] Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
[chrome #0-0] Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
[chrome #0-0]     at /home/przemuh/project/tests/functional/node_modules/mocha/lib/runnable.js:380:21
[chrome #0-0]     at /home/przemuh/project/tests/functional/node_modules/wdio-mocha-framework/build/adapter.js:311:28
[chrome #0-0]     at process._tickDomainCallback (internal/process/next_tick.js:129:7)`

Linked mocha issue: https://github.com/mochajs/mocha/issues/2407

So my question is: Do you plan to increase mocha version in wdio-mocha-framework package.json ?

**Comment by christian-bromann** [comment]
@przemuh wdio-mocha-framework already uses latest Mocha version (see [here](https://github.com/webdriverio/wdio-mocha-framework/blob/v0.5.8/package.json#L31))
