### ISSUE TITLE
Compilers are not included before requires, so requires cannot be written with the compiler's syntax

### ISSUE THREAD

**Issue by snoozbuster** [webdriverio/wdio-mocha-framework#71]
I think the problem line is https://github.com/webdriverio/wdio-mocha-framework/blob/master/lib/adapter.js#L69. The `...requires, ...compilers` should be switched to `...compilers, ...requires` so that the compilers are included first. This would allow the requires to be written using whatever compiler you are using, instead of forcing the requires to be written using the language level that your version of node supports.

**Comment by christian-bromann** [comment]
See #72
