### ISSUE TITLE
Can't install package on node 7.4.0+, Windows

### ISSUE THREAD

**Issue by Lazys** [webdriverio/wdio-mocha-framework#74]
I'm not able to install wdio-mocha-framework (there is the same problem with wdio-cucumber-framework and wdio-jasmine-framework) on node 7.4.0, 7.10.1, 8.2.0, so I suppose that this is a problem with all node verisons starting from 7.4.0. 

On the last LTS node version - 6.11.1 everything works fine. 

Probably there is some problem with node-gyp (or fibers?), but I was not sure where I should report this issue. I've tried all installation instructions from https://github.com/nodejs/node-gyp, but it doesn't help. On node 6.11.1 it's installing fine, without any additional work needed, but on any newer node version nothing helps.

Error log from, for example, node 8.2.0:1
PS C:\Users\me\Desktop\webdrivertests> npm install wdio-mocha-framework --save-dev

fibers@1.0.15 install C:\Users\me\Desktop\webdrivertests\node_modules\wdio-sync\node_modules\fibers
node build.js || nodejs build.js

C:\Users\me\Desktop\webdrivertests\node_modules\wdio-sync\node_modules\fibers>if not defined npm_config_node_gyp
node "C:\Users\me\AppData\Roaming\nvm\v8.2.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
de-gyp.js" rebuild --release )  else (node "" rebuild --release )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable

gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\me\AppData\Roaming\nvm\v8.2.0\node_modules\npm\node_mod
les\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\me\AppData\Roaming\nvm\v8.2.0\node_modules\npm\node_modu
es\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\me\AppData\Roaming\nvm\v8.2.0\node_modules\npm\node_modules\graceful-fs\polyfills.
s:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\nvm\\v8.2.0\\node_module
\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\me\Desktop\webdrivertests\node_modules\wdio-sync\node_modules\fibers
gyp ERR! node -v v8.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN webdrivertests@1.0.0 No description
npm WARN webdrivertests@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2017-07-21T07_57_47_662Z-debug.log

**Comment by christian-bromann** [comment]
> Windows + OS X instructions here: https://github.com/nodejs/node-gyp

Make sure you have node-gyp installed on your machine.

**Comment by Lazys** [comment]
I've mentioned that I was trying to install node-gyp:

>  I've tried all installation instructions from https://github.com/nodejs/node-gyp, but it doesn't help. On node 6.11.1 it's installing fine, without any additional work needed, but on any newer node version nothing helps.

**Comment by christian-bromann** [comment]
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable

Maybe this is the problem
