### ISSUE TITLE
Mocha test pass if there is some Error 

### ISSUE THREAD

**Issue by ignachiou** [webdriverio/wdio-mocha-framework#90]
I'm doing some api rest test with wdio, mocha, chai and chai-http async mode. When i run the test it show me via console the error in white letters (should be red) but the mocha test pass (green check). It should throw me a bad test, what could be happening here?

This is the code:

        var chai = require('chai');
        var chaiHttp = require('chai-http');
        global.expect = chai.expect;
        chai.Should();
        chai.use(chaiHttp);

        var username = 'salvador.salvatierra@alegra.com';
         var token = 'a5ff7f1063582fd0140d';

        describe('Se consulta a la lista de contactos a traves de la API rest', function(){
	
	it('Se hace un request GET al endpoint /contacts', function(){
			
		chai.request('https://app.alegra.com/api/v1/contacts')
		.get('/')
		.set('Accept','application/json')
		.query({limit:'10', order_direction: 'DESC', order_field: 'id'})
		//.auth(username,token)
		.then(function(res) {
			console.log(res);
			expect(res).to.have.status(200);
			//res.body.should.be.a.json;
		})
		.catch(function (err){
				console.log(err.rawResponse);
				throw new Error('Error');
						
		})		
		
	});
	
       });

This is the package.json:

         "devDependencies": {
                 "chai": "^4.1.1",
                 "chai-http": "^3.0.0",
                 "wdio-dot-reporter": "0.0.8",
                 "wdio-mocha-framework": "^0.5.11",
                 "wdio-selenium-standalone-service": "0.0.8",
                 "wdio-spec-reporter": "^0.1.2",
                 "webdriverio": "^4.8.0"
             }

**Comment by christian-bromann** [comment]
Your code runs asynchronous code. Make sure your properly handle promises:
```js
it('Se hace un request GET al endpoint /contacts', function(){
		
	return chai.request('https://app.alegra.com/api/v1/contacts')
	.get('/')
	.set('Accept','application/json')
	.query({limit:'10', order_direction: 'DESC', order_field: 'id'})
	//.auth(username,token)
	.then(function(res) {
		console.log(res);
		expect(res).to.have.status(200);
		//res.body.should.be.a.json;
	})
	.catch(function (err){
			console.log(err.rawResponse);
			throw new Error('Error');
					
	})		
	
});
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
